table Movimentação
	lineageTag: e24ffb57-4e69-4ac6-8811-a4fa8e6a0bcc

	measure 'soma de valor' = ```
			SUM('Movimentação'[Valor]) 
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d26ed8fd-a7e9-42e7-b74e-f6fcc0ae5ed3

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure lucro = ```
			SUM('Movimentação'[Valor com sinal]) 
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: a6a0523d-b296-4997-ab00-757fdbcd3d70

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Cliente
		dataType: string
		lineageTag: f000738d-c969-411f-8c6b-dff60d5f109b
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: double
		lineageTag: 89af72a7-e298-426c-bde5-a0580666e5c8
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Data da Movimentação'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 63c458ea-aa3f-4f1f-a218-33a5b0103607
		summarizeBy: none
		sourceColumn: Data da Movimentação

		variation Variation
			isDefault
			relationship: 110fb18f-fd30-44de-9e8e-68f253f11230
			defaultHierarchy: LocalDateTable_23030cad-9bb7-4a63-989d-88a82382d145.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Conta Contábil'
		dataType: int64
		formatString: 0
		lineageTag: 646965d5-e5e9-44fe-96f3-bd9033b20eb3
		summarizeBy: sum
		sourceColumn: Conta Contábil

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Movimento'
		dataType: string
		lineageTag: 4e1153d9-a1ec-4c8a-9856-083bc030b71a
		summarizeBy: none
		sourceColumn: Tipo de Movimento

		annotation SummarizationSetBy = Automatic

	column 'Natureza da Conta'
		dataType: string
		lineageTag: 5cc6576a-0798-4b9d-b636-67c477da1087
		summarizeBy: none
		sourceColumn: Natureza da Conta

		annotation SummarizationSetBy = Automatic

	column 'Classe Operacional'
		dataType: string
		lineageTag: f81cab99-5744-4cb4-9814-73d6a2baf92e
		summarizeBy: none
		sourceColumn: Classe Operacional

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Saída'
		dataType: string
		lineageTag: c558516f-1b46-4007-bf14-44b37e2601f6
		summarizeBy: none
		sourceColumn: Tipo de Saída

		annotation SummarizationSetBy = Automatic

	column 'Valor com sinal'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 80eb14b3-02f3-4757-97fc-cf96046fe10c
		summarizeBy: sum
		sourceColumn: Valor com sinal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition Movimentação = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\Millena\Downloads\BI_Financeiro_curso\Base de Dados\Base de Dados.xlsx"), null, true),
				    Movimentação_Sheet = Fonte{[Item="Movimentação",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Movimentação_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Cliente", type text}, {"Valor", type number}, {"Data da Movimentação", type date}, {"Conta Contábil", Int64.Type}, {"Tipo de Movimento", type text}, {"Natureza da Conta", type text}, {"Classe Operacional", type text}, {"Tipo de Saída", type text}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Valor com sinal", each if [Natureza da Conta] = "Receita" then [Valor] else -[Valor]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"Valor com sinal", Currency.Type}})
				in
				    #"Tipo Alterado1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

